### ISSUE TITLE
Is it possible to compile sync service to wasm binary and make it as part of node module?

### ISSUE THREAD

**Issue by pgcr71** [electric-sql/electric#1040]
I have no knowledge on the internals of electricsql. but
Is it possible to compile sync service to wasm binary and make it as part of node module. so that end users doesn't need to install elixir

**Comment by alco** [comment]
Hey @pgcr71 :wave: 

We distribute Electric as a [Docker image](https://electric-sql.com/docs/deployment/docker) hosted on Docker Hub, so if you're OK with running it as a Docker container, there's no need to install Elixir or build Electric from source.

Compiling the sync service to WASM is not really an option since we're relying on the [BEAM virtual machine](https://www.erlang-solutions.com/blog/erlangs-virtual-machine-the-beam/) to utilize all available cores, keep the memory footprint low and have direct access to socket APIs for internal connections (sync service to Postgres) and external client connections.
