### ISSUE TITLE
npm run build fails after project generation

### ISSUE THREAD

**Issue by agdolla** [electric-sql/electric#1114]
Hello!

After I created a new project and tried to build it, I get two errors:

`npx create-electric-app@latest my-app --template react`
`npm run build`

> my-app@0.1.0 build
> tsc && vite build

src/generated/client/index.ts:3:38 - error TS6133: 'Relation' is declared but its value is never read.

3 import { type TableSchema, DbSchema, Relation, ElectricClient, type HKT } from 'electric-sql/client/model';
                                       ~~~~~~~~

src/generated/client/index.ts:298:11 - error TS2430: Interface 'ItemsGetPayload' incorrectly extends interface 'HKT'.
  Types of property 'type' are incompatible.
    Type 'ItemsGetPayload<this["_A"]>' is not assignable to type 'Record<string, any> | undefined'.
      Type '"Please either choose `select` or `include`" | Items | { [x: string]: never; [x: number]: never; }' is not assignable to type 'Record<string, any> | undefined'.
        Type 'string' is not assignable to type 'Record<string, any>'.

298 interface ItemsGetPayload extends HKT {
              ~~~~~~~~~~~~~~~

Found 2 errors in the same file, starting at: src/generated/client/index.ts:3

**Comment by msfstef** [comment]
Thank you for reporting the error!

The first error about `Relation` being declared but never read is going to be fixed by this PR https://github.com/electric-sql/electric/pull/1117 hopefully part of the next release - in the meantime you can either remove it yourself or add a @ts-ignore annotation for it

The second error seems to occur with Typescript 5.4 - reverting to typescript version 5.3.3 will no longer result in this error. I will be looking into this, but fixing TS to 5.3.3 in the meantime should allow you to compile the client.

**Comment by agdolla** [comment]
@msfstef  ok thanks I try with TS 5.3.3
