### ISSUE TITLE
Message type doesn't allow discriminating between a ControlMessage and ChangeMessage at the type level.

### ISSUE THREAD

**Issue by samwillis** [electric-sql/electric#1453]
The code below is unable to discriminate that the message is a `ChangeMessage`:

```ts
if (message.headers.action === "insert") {
  // message is still ControlMessage | ChangeMessage
}
```

It would be nice if there was a way to discriminate them without having to manually use `as`

**Comment by kevin-dp** [comment]
It does not seem possible to discriminate on the value of a key that may or may not be present. It's only possible to discriminate on a key that is known to be present but that has different values in different types.

For example:
```ts
export type ControlMessage = {
  tag: 'Control'
  headers: Header
}

export type ChangeMessage<T> = {
  tag: 'Change'
  key: string
  value: T
  headers: Header & { operation: `insert` | `update` | `delete` }
  offset: Offset
}

// Define the type for a record
export type Message<T extends Value = { [key: string]: Value }> =
  | ControlMessage
  | ChangeMessage<T>

const message: Message = undefined as unknown as Message

if (message.tag === 'Change') {
    message.value // `message` is typed as `ChangeMessage`
} else {
    message.headers // `message` is typed as `ControlMessage`
}
```

However, we don't have this `tag` property on which we can discriminate.
So let's change the `Header` interface for a second:
```ts
interface Header {
  //[key: string]: Value
  foo: number
}
```

Now let's try to discriminate as you did:
```ts
if (message.headers.operation === "insert")
```

uh oh... type error:
```
Property 'operation' does not exist on type 'Header | (Header & { operation: "insert" | "update" | "delete"; })'.
```

Right... we can't be sure that the `operation` property exists on that union type. So let's try to narrow the type using the `in` operator:
```ts
if ('operation' in message.headers) {
    message.value // error 
}
```

Unfortunately, narrowing using the `in` operator on a nested property (`message.headers`) does not seem to work in TypeScript.

So, why didn't TypeScript throw an error in your original example `message.headers.operation === "insert"` ?
Because `Header` is defined as:
```ts
interface Header {
  [key: string]: Value
}
```
So, any key that is a string is accepted, and thus `headers.operation` typechecks but it will not narrow as you were expecting since a `ControlMessage` could also have an `operation` property in its headers.

**If you need to narrow it down, you can use the `in` operator on a top-level property:**
```ts
if ('key' in message) {
  message.value
} else {
  message.headers
}
```

**Comment by kevin-dp** [comment]
Perhaps a cleaner approach is to abstract these details away behind two helper functions for doing the narrowing:

```ts
function isChangeMessage(message: Message): message is ControlMessage {
  return 'key' in message
}

function isControlMessage<T extends Value = { [key: string]: Value }>(message: Message<T>): message is ChangeMessage<T> {
  return !isChangeMessage(message)
}
```

**Comment by KyleAMathews** [comment]
👍 helper functions sound nice. That way it's easy to keep expanding if necessary.

**Comment by balegas** [comment]
Related with #1433

**Comment by msfstef** [comment]
Added the helpers to close this issue https://github.com/electric-sql/electric/pull/1572

If we move to a top level attribute to distinguish messages then we can think about https://github.com/electric-sql/electric/issues/1433
