### ISSUE TITLE
Streaming initial sync of large shapes.

### ISSUE THREAD

**Issue by thruflo** [electric-sql/electric#1458]
We currently:

```
[query a shape] -> [save to log] -> [serve log]
```

This is slow to first byte for large shapes.

We should:

```
[query a shape] -> [start streaming into log] -> [start serving the log] -> ... stream everything through ...
```

**Comment by chasers** [comment]
Is there something here to be done with `pg_export_snapshot` perhaps? 

DuckDb can query Postgres directly with this method on large tables faster than Postgres itself:

https://duckdb.org/2022/09/30/postgres-scanner.html

**Comment by KyleAMathews** [comment]
Generally we need to stick to vanilla postgres so we're as widely usable as possible as many people can't or won't add custom extensions.

This issue is more about not waiting to get the entire query back before starting to send data to the client. Query time hasn't been the bottleneck generally.

This particular issue was actually solved a couple of days ago in https://github.com/electric-sql/electric/pull/1517 so I'll close this now.

**Comment by chasers** [comment]
It's not an extension. It's a way to copy large tables, or large subsets of tables in parallel and do it transactionally with native Postgres functions.

Not sure if applicable or usable, but seems like if you want to get a lot of data to a shape quickly this could be a way to do it.

**Comment by KyleAMathews** [comment]
Ah I see! Yeah I didn't know what it was clearly 😅

Hmm yeah, I suspect it wouldn't be much faster if at all as we'd need to parse the data and perhaps do additional processing. DuckDB has that all built and heavily optimized so it's an easier lift. 

So sticking with querying seems good for now but it's definitely something we'll keep in the back of our minds as we scale up to gb/tb sized shapes.
