### ISSUE TITLE
Expose from client when it's not up-to-date with server

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#1468]
This could be due to temporary network/server issues or if the client is coming back from being offline and hasn't yet downloaded & applied all the updates.

- [ ] `isUpToDate` should be set to false
- [ ] expose variable with the number of ms since the last successful sync

**Comment by kevin-dp** [comment]
Nice idea to expose a variable that is the time elapsed since last sync!

Regarding `isUpToDate`, i'm not sure about setting it to false.
Internally, it's used to determine whether to use live mode or not. If it turns out we're not up to date, we will get the part of the log we are missing and will then go back into live mode on the latest offset. So internally, i don't think there's a need to put `isUpToDate` to false.

However, we also expose `isUpToDate` externally, which may lead users to think they are up to date while it may be that they were up to date 1 hour ago and that we failed to sync since then. But it's hard to tell when `isUpToDate` should become false... because there's no way to know for sure other than contacting Electric.

The point i'm trying to make is that if we pessimistically put `isUpToDate` to false because the last N fetch requests failed, that doesn't necessarily mean we are out of date, we wil only know when we manage to reach Electric again. So maybe, we want an internal `_isUpToDate` that we keep as it is now, and have an external `isUpToDate` that is true if we managed to sync recently, e.g. if `timeSinceLastSync < UP_TO_DATE_THRESHOLD`. One could also argue that exposing the time elapsed since last sync is enough for this purpose and clients can decide for themselves whether they are up to date or not.

**Comment by msfstef** [comment]
I like the idea of an `UP_TO_DATE_THRESHOLD`, perhaps a configurable one with a sensible default?

**Comment by KyleAMathews** [comment]
> But it's hard to tell when isUpToDate should become false...

Wouldn't it just be anytime there's a fetch error? https://github.com/electric-sql/electric/blob/b322b957a1010c6450175001b5519b9567558fbc/packages/typescript-client/src/client.ts#L390-L412

But yeah, I see you're point. Maybe `isUpToDate` is the wrong variable name for what I'm thinking. Basically what I want is what we had in the old electric where you could see if you were connected to Electric or not. There's not an exact analogy to http long-polling as we don't have a persistent connection but `isConnected` could be true once we've successfully fetched data and get switched to false as soon as there's any fetch errors.

> UP_TO_DATE_THRESHOLD

NO OPTIONS! 😛

**Comment by kevin-dp** [comment]
@KyleAMathews i see!
So, let's keep `isUpToDate` but make it private, and introduce a public `isConnected` variable that is put to false on a fetch error.

**Comment by KyleAMathews** [comment]
Great!
