### ISSUE TITLE
Ionic Demo is missing

### ISSUE THREAD

**Issue by Imaginativeone** [electric-sql/electric#1549]
When will it be back?

**Comment by osdiab** [comment]
Hi, the old ionic demo has a snippet where it actually uses the Capacitor SQLite plugin to store data locally rather than using IndexedDB like the existing examples work:

https://github.com/electric-sql/electric-old/blob/b4da7af0e45ed7c34a5069640922ab8acca389bd/examples/ionic-demo/src/electric.tsx#L65

Is that something that is not encouraged/possible anymore? I ask since Capacitor docs specifically talk about how [you ought not use IndexedDB for persisting data](https://capacitorjs.com/docs/guides/storage#why-cant-i-just-use-localstorage-or-indexeddb), so would the impact of this potentially be that the local store can get nuked and force resyncs when that happens?
