### ISSUE TITLE
Add starters support

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#1583]
It's very common for tools to have starters or templates or boilerplates that people can start new projects from (or at least see best practices if they're adding a tool to an existing project).

Examples:
- next.js — https://remix.run/docs/en/main/guides/templates
- remix — https://remix.run/docs/en/main/guides/templates
- vite — https://vitejs.dev/guide/#scaffolding-your-first-vite-project

We'll want a `create-electric` package so people can run e.g. `npx create-electric react`.

We'll have official starters and then anyone can use the same create package to setup their own.

We don't want to use the official npm create setup as I believe in only supports cloning bare git repos — which are a pain to support. Remix maintains all their official templates in their main repo which is ideal as then PR making breaking changes can easily update starters at the same time as they update package code and examples.

There's lots of prior art on design and implementation for this. Basically they clone the repo and copy over files. They also often init a git repo and sometimes run install (though having the user do that is easier then asking them what package manager they use).

When we get close to implementing this, let's jam a bit more on specifics.

Initial starters to support:
- React w/ Next.js & useShape
- React w/ Remix & useShape
- React w/ Next.js & pgilte
- Vue w/ Nuxt

Should the starter just have implemented the basic example? We could just move the existing next.js example into a templates folder then.

**Comment by thruflo** [comment]
We obviously had https://www.npmjs.com/package/create-electric-app / https://github.com/electric-sql/electric-old/tree/main/examples/starter previously.

To express a counter argument: previously we needed a starter because the stack was complex. Now the stack and the client are much simpler. Would it be better to focus on guides rather than turnkey starters? That way we maintain less code, users start with their framework's starter and we show how to mix in Electric. Which is a better pattern for (a) incremental adoption for brownfield apps and (b) actually understanding how to integrate Electric.

Partly I'm motivated to argue this because starter maintenance previously proved quite fiddly, compared with straight examples, which are easier to maintain and don't require us to wrap up so much optionality. So a guide per framework/stack and examples for specific configurations including PGlite?

**Comment by KyleAMathews** [comment]
Yeah that's a good argument. Definitely start with guides (we need them anyways) and only add starters if guides prove not enough. 

I'll close this and replace it with an issue for guides.

**Comment by rashidpathiyil** [comment]
Any Examples for Nuxt + Nitro + Drizzle ?
