### ISSUE TITLE
CamelCased Tables cause "table name does not match expected format"

### ISSUE THREAD

**Issue by AndryHTC** [electric-sql/electric#1764]
Example:
`public.Test`

If I request the shape:
`http://localhost:3000/v1/shape/Test` -> `{
	"root_table": [
		"table name does not match expected format"
	]
}`

`http://localhost:3000/v1/shape/test` -> `{
	"root_table": [
		"table not found"
	]
}`

But if I alter the name of the table to lowercase `public.test`, it works.

**It should accept any table format as shape.**

**Comment by kevin-dp** [comment]
Hi @AndryHTC,

Thanks for reporting this. Current schema and table name validation is quite strict as it is based on this regex:
```
^((?<schema>([a-z_][a-zA-Z0-9_]*|"(""|[^"])+"))\.)?(?<table>([a-z_][a-zA-Z0-9_]*|"(""|[^"])+"))$
```

As you can see from the regex, we require the first character to be a lowercase letter, an underscore, or a quote. I remember implementing it like that based on this paragraph from the [PostgreSQL documentation](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS):

> SQL identifiers and key words must begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) or an underscore (_). Subsequent characters in an identifier or key word can be letters, underscores, digits (0-9), or dollar signs ($). Note that dollar signs are not allowed in identifiers according to the letter of the SQL standard, so their use might render applications less portable.

I interpreted this as, names cannot start with uppercase letters. But, after testing it this morning, table names starting with an uppercase letter seem perfectly valid. For now, you can work around this issue by quoting the table name: "Test".

We will need to modify the validation to:
- allow names starting with uppercase letters
- allow $ sign in names
- Allow diacritical marks and non-Latin letters

Note that these restrictions only apply for non-quoted names, when they are quoted, names can contain any character. This can always be achieved by quoting the table when requesting the shape, but for convenience we should perhaps also allow these characters without quoting.

**Comment by AndryHTC** [comment]
@kevin-dp great, it works with quotes so I can continue with the implementation.

What I don't understand is why you're so strict with the table format 😄

**Comment by kevin-dp** [comment]
Indeed, we should relax the validation and just follow Postgres semantics by making unquoted names case insensitive.

**Comment by kevin-dp** [comment]
Here are 2 candidate regexes to validate table names.
The first one is less strict as it allows any character (except quotes) to occur in unquoted names:

```regex
^((?<schema>([^"]+|"(""|[^"])+"))\.)?(?<table>([^"]+|"(""|[^"])+"))$
```

Downside of this approach is that invalid names will make it to Postgres which will complain and error reporting won't be optimal.

Second regex is a stricter regex but it should fulfill Postgres' naming rules:

```regex
^((?<schema>([\p{L}_][\p{L}0-9_$]*|"(""|[^"])+"))\.)?(?<table>([\p{L}_][\p{L}0-9_$]*|"(""|[^"])+"))$
```

This regex supports any unicode letter as well as digits, underscores and dollar signs. Advantage of this approach is that it detects invalid names early and responds with an appropriate error message.

**Comment by kevin-dp** [comment]
@KyleAMathews asked for Electric to match the case insensitive behavior of Postgres. There are some corner cases with regard to case insensitivity when using non-latin capital letters:
```SQL
CREATE TABLE Foo (a INT PRIMARY KEY);
CREATE TABLE Δabc (a INT PRIMARY KEY);

\dt
        List of relations
 Schema | Name | Type  |  Owner   
--------+------+-------+----------
 public | foo  | table | postgres
 public | Δabc | table | postgres
(2 rows)

SELECT relname FROM pg_class WHERE relkind = 'r';
         relname          
--------------------------
 foo
 Δabc
```

Notice how Postgres lowercased the "F" in `Foo` but didn't lowercase the capital delta "Δ". Thus, we should not lowercase unquoted schema/table names ourselves by doing e.g.:
```ex
iex(1)> String.downcase("Δabc")
"δabc"
```
Because as you can see, this also lowercases non-latin letters. We could do some custom logic to only lowercase latin letters but that seems a recipe for disaster as there are probably some other corner case we aren't aware of.

Thus, if we want to keep Postgres' behavior, we want to feed the schema/table names to Postgres and let Postgres handle it in its case insensitive way. However, we have queries like these:
```SQL
SELECT relname FROM pg_class WHERE relname = 'Foo' AND relkind = 'r';
```
As you can see from the first code snippet, the `relname` is stored as a string. Hence, we are obliged to pass it as a string `'Foo'` (instead of an identifier) and won't get Postgres case insensitive behavior.

Furthermore, we use the schema and table names internally as strings to determine if a change matches a shape, etc. Thus, we need a way to query Postgres to get the actual name for the user provided schema/table name. We can use the regclass type (which is an oid) for that and use that oid to query the relation name:
```SQL
SELECT relname FROM pg_class WHERE relkind = 'r' AND oid = 'Foo'::regclass;
 relname 
---------
 foo
(1 row)
```

It also works when the user provides a quoted name:
```SQL
CREATE TABLE "FooBar" (a INT PRIMARY KEY);
SELECT relname FROM pg_class WHERE relkind = 'r' AND oid = '"FooBar"'::re
gclass;
 relname 
---------
 FooBar
(1 row)
```
Thus, we can use this query to turn the user-provided table name into the actual Postgres table name.

**Comment by samwillis** [comment]
I want to just clarify that Postgres *isn't* case insensitive, that would imply that a table created with:

```sql
CREATE TABLE "MyTable" (
   ....
)
```

was queryable with:

```sql
SELECT * FROM MyTable
```

but that query will fail.

Postgres has case insensitive SQL syntax, and lowercases ASCII characters in unquoted identifiers. Other than that it is case sensitive.

It's also important to note that Prisma and many other ORMs will use CamelCase for table names - they automatically quote all identifies in generated SQL.

We have two options:

1. Match the "behaviour" of Postgres, as though the table name, quote and all, are pasted into the SQL directly. So pass it to Postgres unquote, and include the quotes when they are included in the parameter. A user will have to quote the table name in the url/parameter if it is stored as CamelCase, just as they would with SQL.
2. Always quote the identifier when passed through to Postgres. The parameter is then fully case sensitive.

Adding any introspection to check table names is pure overhead, I would argue against that.

With the context of #1771 which suggests moving the table name out of the path and to a parameter, along with a look at other APIs (such as [Postgrest](https://docs.postgrest.org/en/v12/)), I would argue that we should always quote the table name when passed to Postgres (as Postgrest does). The table name will be % coded in the url parameter, and so it will correctly handle any url-unsafe chars. The only edge case we need to handle is a quote mark in a table name, but this is just replaced with a double quote (`my"table` becomes `my""table`).

Quoting also removes all need to use a regex to validate a table name, and eliminates the risk of a sql injection missed by that validation.

It seems to me that making this change at the same time as moving to a url param (see #1771) would combines two breaking changes into one, and results in a cleaner API.

**Comment by kevin-dp** [comment]
@samwillis yep that's what i meant when i say "case insensitive". It's case insensitive when unquoted and case sensitive when quoted.

**Comment by balegas** [comment]
@KyleAMathews what's your take? I think What @samwillis is proposing makes sense and I think deciding this before #1771  and #1676 would be useful.

**Comment by KyleAMathews** [comment]
@balegas are they proposing something different? Did you look at Kevin's pr?

**Comment by KyleAMathews** [comment]
Ok here's a new angle:

API design works on the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

> People are part of the system. The design should match the user's experience, expectations, and [mental models](https://en.wikipedia.org/wiki/Mental_model).

So the question of which of these two models is best hinges on which is least astonishing/surprising.

The general rule when wrapping an underlying API is to copy their API exactly because the presumption is people adopting your new wrapper system are already familiar with the underlying system so you don't want to surprise people.

But @samwillis' argument is that SQL has already effectively been wrapped by the ORMs so that a large % of users don't even know about the quoted vs. non-quoted behavior distinction when creating tables. So copying Postgres is more surprising than copying ORMs.

Another way of analyzing this is to identify the surprise that each path creates.

- Matching Postgres means that people will be surprised when they have to use quotes when querying a shape.
- Matching ORM behavior means people will be surprised only if they create a lower-case table and then use upper-case in the shape call (is that it?)

So of the two, matching ORM behavior does seem less surprising. So we should go with that.

**Comment by kevin-dp** [comment]
@KyleAMathews another surprise when matching ORM behavior is the opposite case: when people create an upper-case table and then query it in lowercase (all unquoted). Note that the original implementation was already supporting quoted and unquoted tables. It was just doing a bit too strict validation.

@KyleAMathews can we decide what exactly we want? https://github.com/electric-sql/electric/pull/1776 implements matching Postgres behavior as initially discussed. I'm fine with throwing that away and keeping it as it was before. If we keep it as before, do we skip validation altogether, or validate it according to one of the regexes proposed in https://github.com/electric-sql/electric/issues/1764#issuecomment-2382436820? The stricter regex, however, has a problem with non-latin characters as explained in https://github.com/electric-sql/electric/issues/1764#issuecomment-2385017569.

**Comment by balegas** [comment]
Let me try to express what I think @samwillis proposed and seems right to me.

The definition is: **table name path param is a camel-sensitive unquoted string**. The implementation of this rule is to pass the path param inside quotes to the pg client.

To explain with examples:
- A table defined as "My Table" in PG would be passed in the url param as  `My%20Table`
- This matches the table either if it was defined as MyTable or "MyTable" 
- In Postgres MyTable and myTable are different, but myTable and "myTable" are equivalent, the param value for those cases `MyTable` and `myTable` respectively.

For convenience, we could detect if the user passes the string inside quotes and either accept it or throw an error. 
@kevin-dp, what's the validation needed for this proposal?

**Comment by kevin-dp** [comment]
@balegas Ok, so i understand we want to be case sensitive and not do any validation ourselves + support quotes for corner cases with schema qualified table names, e.g.: `"foo.bar"."baz"`. Implementation is very easy, we just need to remove the validation we originally had.

**Comment by balegas** [comment]
We have a verdict! Because shape where clauses are raw Postgres, we decided that the parameter should follow the same format.
We want error messages to be informtivr
- they should show the tablename/query that was passed to Postgres
- ppoint to documentation where we state how we pass params to Postgres
- give some hints. e.g. if user started table name with uppercase we want to suggest to use quotes

we talked about doing fuzzy matching but we want do it right now because it would require managing a cache of known table.s

**Comment by alco** [comment]
I would argue against going to Postgres for name lookup. Replicating Postgres' identifier parsing is much simpler because it can be implemented as a pure function. Postgres is open source and it's not like its definition of what is an identifier is going to change any time soon: no DB queries or caching required.

I have to admit that Postgres' definition of the `identifier` token (as specified in its [lexer code](https://github.com/postgres/postgres/blob/259a0a99fe3d45dcf624788c1724d9989f3382dc/src/backend/parser/scan.l#L346-L349)) is a bit cryptic: it explicitly mentions the ranges `A-Z`, `a-z` and byte values in the range `\200-\377` (those are octal numbers, in decimal they are 128 to 255), but I think the intent there is to allow any valid UTF-8 code point beyond the 7-bit ASCII Plane, so not only letters. For example, this works in psql:
```
=# create table 🪷(id text);
CREATE TABLE
=# \d
        List of relations
 Schema │ Name │ Type  │  Owner   
────────┼──────┼───────┼──────────
 public │ foo¡ │ table │ postgres
 public │ Δ    │ table │ postgres
 public │ 🪷   │ table │ postgres
```

There is, apparently, a separate validation to determine that the given byte sequence is valid UTF-8 encoding (or any other encoding that the database server is configured to use) because not all sequences of bytes are valid identifiers.

Regardless, the algorithm for lower-casing identifiers is very small and straightforward. Here's its full implementation -
https://github.com/postgres/postgres/blob/259a0a99fe3d45dcf624788c1724d9989f3382dc/src/backend/parser/scansup.c#L55-L73

So it is conceivable that we can implement our own validation of user-provided table identifiers by checking they are valid UTF-8 strings and don't contain certain ASCII characters. Then we can normalize the identifier by implement Postgres' downcasing algorithm to obtain a string that we can use to fetch table info from Postgres and as a cache key for storing table info in memory.
