### ISSUE TITLE
Queue requests and return 429s when the server gets overloaded

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#1770]
Right now we eagerly try to fulfill all shape requests.

Too many requests can crash the server or postgres or trigger timeouts.

We should handle this more gracefully.

First we should queue requests and limit concurrency on fulfilling them.

We should perhaps have one queue for already created shapes vs. ones we're initing as they have different performance characteristics (reading the cached logs is very cheap vs. creating a new shape).

If the queue gets too long, we can start returning requests at the end of the queue with a 429 http code (Too Many Requests). [Clients would need to special-case 429](https://github.com/electric-sql/electric/blob/7f4456529f10b39be453fd206d0ea348233eaf8f/packages/typescript-client/src/fetch.ts#L65-L68) as a retry-able error.

We'll need to figure out heuristics for "too long" of queue — which could be a combination of hard limits + soft limits based on postgres & electric loads i.e. if postgres is slow responding to queries, we could drop concurrency and queue length temporarily.

**Comment by ericallam** [comment]
We're going to be adding rate-limiting at our "proxy" endpoint and returning 429s as well, which sets `x-ratelimit-limit`, `x-ratelimit-remaining`, and `x-ratelimit-reset` headers. Having the client retry by respecting those headers (instead of a simple exponential backoff) would be great.

For reference, the `x-ratelimit-reset` is a unix timestamp in ms.
