### ISSUE TITLE
[Client] Race condition when two performSnapshot run simultaneously

### ISSUE THREAD

**Issue by js2702** [electric-sql/electric#258]
We were debugging an issue on the Dart todo's app where the delete replication wasn't propagating. Only deleting locally. After some tests we discovered that we were triggering multiple times the `potentiallyChanged` in the adapter. Causing the function `performSnapshot` from process.ts to throttle.
What happens is that, after it finishes the throttling and the function actually executes, if it takes more time than the throttled window, it can happen that a second `performSnapshot` starts. What this causes is that the clearTags and tags properties can get emptied when sending the delete operation on top of sending two different delete operations at the same time.

Would it make sense to ignore a performSnapshot event if one is already running? This can also happen on the Typescript client although it's trickier to trigger.

https://github.com/electric-sql/electric/blob/8f68c1b49c78909ef1355dadbf16c9a320bb2e23/clients/typescript/src/satellite/process.ts#L551

**Comment by icehaunter** [comment]
> trickier to trigger
How so, I wonder? what's the difference here between TS and Dart clients?

**Comment by davidmartos96** [comment]
@icehaunter  No difference at all, but an extra `sleepAsync` in the TS performSnapshot was needed to slow down the execution and trigger it more effectively.
On the Dart client, we discovered the race condition by chance due to a bug in the adapter calling `potentiallyChanged` even from the Satellite statements.

I'll share the places in the code where the tags "get lost" before sending the delete op.

After pressing delete here is what happens in performSnapshot (I'll tag each line to identify parallel executions):

execution 1:  `oplogEntry.clearTags: ["847e31fd-2eda-4fa7-a2d4-92737c7df1d9@1689677905555"]  shadowEntry.tags: []`
https://github.com/electric-sql/electric/blob/6026cedbe2f635127d7ccc8a2e5486ce66213470/clients/typescript/src/satellite/process.ts#L589

execution 2: `missing` it's a list with one element but with `clearTags=[]` which in return sends the delete op without tags and doesn't replicate properly
https://github.com/electric-sql/electric/blob/6026cedbe2f635127d7ccc8a2e5486ce66213470/clients/typescript/src/satellite/process.ts#L610

Hope that gives more context

**Comment by icehaunter** [comment]
Internal ref VAX-788
