### ISSUE TITLE
[VAX-1058] Handle indexes in the generator

### ISSUE THREAD

**Issue by balegas** [electric-sql/electric#457]
The generator breaks if Pg table has an index as reported [here](https://discord.com/channels/933657521581858818/1079688869852753981/1153841371938045972).

* [Reproducible error repo](https://discord.com/channels/933657521581858818/1079688869852753981/1153841745319182447).

Reported by @hugodutka

**Comment by balegas** [comment]
@kevin-dp when analysing root cause, please make sure necessary changes are valid if we move introspection to Pg. We can handle this issue after that, if necessary.

**Comment by kevin-dp** [comment]
I was able to reproduce the bug and found the cause.
The ts-client fetches the migrations from Electric and then builds them and bundles them in the client.

When building the migrations, the ts-client expects that every `SatOpMigrate` message contains a `table` field of type `SatOpMigrate_Table`. However, that field is not present if the migration only contains an index creation.

I can see 2 solutions:
1) The TS-client checks whether the message contains a table field. If not, it ignores the migration altogether
2) Electric makes sure to also send the table information for index creations

Maybe we even want to do both.
1) will be needed anyway because the Satellite protocol defines the `SatOpMigrate.table` field to be optional.
So it must correctly handle the absence of that field. Unless we would make that field required in the protocol.

**Comment by magnetised** [comment]
@kevin-dp why do we need the table information in every migration? a create index operation doesn't affect any table structure, so what's the requirement for table information?

**Comment by kevin-dp** [comment]
@magnetised Totally right. The current ts-client naively thinks that every migration changes at least some table structure and thus needs that information to add/modify any triggers. I will remove that assumption from the client and simply not try to build any triggers for it if the table information is absent.
