### ISSUE TITLE
[VAX-1074] Database does not exist / support running the generator twice

### ISSUE THREAD

**Issue by thruflo** [electric-sql/electric#489]
Running the generator twice to create two different projects runs into a database name not found error.

As per report at [https://discord.com/channels/933657521581858818/1079688869852753981/1154842122571223091](https://discord.com/channels/933657521581858818/1079688869852753981/1154842122571223091)

<sub>From [SyncLinear.com](https://synclinear.com) | [VAX-1074](https://linear.app/electric-sql/issue/VAX-1074/database-does-not-exist-support-running-the-generator-twice)</sub>

**Comment by barbalex** [comment]
I am having a similar issue which makes it impossible (?) for me to start working with electric.

What I have done:
```
npx create-electric-app@latest capturing_electric_2
cd capturing_electric_2
npm i
npm run backend:start
npm run db:migrate
```

The result:
```
PS C:\Users\alexa\capturing_electric_2> npm run backend:start

> capturing_electric_2@0.1.0 backend:start
> docker compose --env-file backend/compose/.envrc -f backend/compose/docker-compose.yaml up

[+] Running 2/2
 ✔ Container compose-postgres-1  Created                                                                                                                                                                                                                                  0.4s 
 ✔ Container compose-electric-1  Recreated                                                                                                                                                                                                                                0.2s 
Attaching to compose-electric-1, compose-postgres-1
compose-postgres-1  | 
compose-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
compose-postgres-1  | 
compose-postgres-1  | 
compose-postgres-1  | 2023-09-25 12:02:39.353 GMT [1] LOG:  starting PostgreSQL 14.9 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
compose-postgres-1  | 2023-09-25 12:02:39.353 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
compose-postgres-1  | 2023-09-25 12:02:39.353 GMT [1] LOG:  listening on IPv6 address "::", port 5432
compose-postgres-1  | 2023-09-25 12:02:39.382 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
compose-postgres-1  | 2023-09-25 12:02:39.389 GMT [22] LOG:  database system was shut down at 2023-09-21 10:04:56 GMT
compose-postgres-1  | 2023-09-25 12:02:39.416 GMT [22] LOG:  recovered replication state of node 1 to 0/0
compose-postgres-1  | 2023-09-25 12:02:39.422 GMT [1] LOG:  database system is ready to accept connections
compose-postgres-1  | 2023-09-25 12:02:39.457 GMT [29] LOG:  logical replication apply worker for subscription "postgres_1" has started
compose-electric-1  | 12:02:40.058 pid=<0.2195.0> [info] Running Electric.Plug.Router with Bandit 1.0.0-pre.14 at 0.0.0.0:5133 (http)
compose-electric-1  | 12:02:40.058 pid=<0.2812.0> origin=postgres_1 [info] connect: %{database: ~c"capturing_electric_2", host: ~c"postgres", port: 5432, ssl: false, timeout: 5000, username: ~c"postgres"}
compose-postgres-1  | 2023-09-25 12:02:40.061 GMT [29] ERROR:  could not connect to the publisher: connection to server at "electric" (172.21.0.3), port 5433 failed: FATAL:  Electric replication is not ready, missing schema for postgres_1
compose-postgres-1  | 2023-09-25 12:02:40.062 GMT [1] LOG:  background worker "logical replication worker" (PID 29) exited with exit code 1
compose-postgres-1  | 2023-09-25 12:02:40.066 GMT [30] FATAL:  database "capturing_electric_2" does not exist
```

log in docker, compose-electric-1:
```
2023-09-25 14:02:40 12:02:40.058 pid=<0.2195.0> [info] Running Electric.Plug.Router with Bandit 1.0.0-pre.14 at 0.0.0.0:5133 (http)
2023-09-25 14:02:40 12:02:40.058 pid=<0.2812.0> origin=postgres_1 [info] connect: %{database: ~c"capturing_electric_2", host: ~c"postgres", port: 5432, ssl: false, timeout: 5000, username: ~c"postgres"}
2023-09-25 14:02:40 12:02:40.066 pid=<0.2812.0> origin=postgres_1 [error] initialization for postgresql failed with reason: {:error, {:error, :fatal, "3D000", :invalid_catalog_name, "database \"capturing_electric_2\" does not exist", [file: "postinit.c", line: "885", routine: "InitPostgres", severity: "FATAL"]}}
```
log in docker, compose-postgres-1:
```
2023-09-25 14:02:39 
2023-09-25 14:02:39 PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-09-25 14:02:39 
2023-09-25 14:02:39 2023-09-25 12:02:39.353 GMT [1] LOG:  starting PostgreSQL 14.9 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
2023-09-25 14:02:39 2023-09-25 12:02:39.353 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-09-25 14:02:39 2023-09-25 12:02:39.353 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2023-09-25 14:02:39 2023-09-25 12:02:39.382 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-09-25 14:02:39 2023-09-25 12:02:39.389 GMT [22] LOG:  database system was shut down at 2023-09-21 10:04:56 GMT
2023-09-25 14:02:39 2023-09-25 12:02:39.416 GMT [22] LOG:  recovered replication state of node 1 to 0/0
2023-09-25 14:02:39 2023-09-25 12:02:39.422 GMT [1] LOG:  database system is ready to accept connections
2023-09-25 14:02:39 2023-09-25 12:02:39.457 GMT [29] LOG:  logical replication apply worker for subscription "postgres_1" has started
2023-09-25 14:02:40 2023-09-25 12:02:40.061 GMT [29] ERROR:  could not connect to the publisher: connection to server at "electric" (172.21.0.3), port 5433 failed: FATAL:  Electric replication is not ready, missing schema for postgres_1
2023-09-25 14:02:40 2023-09-25 12:02:40.062 GMT [1] LOG:  background worker "logical replication worker" (PID 29) exited with exit code 1
2023-09-25 14:02:40 2023-09-25 12:02:40.066 GMT [30] FATAL:  database "capturing_electric_2" does not exist
```

**Comment by kevin-dp** [comment]
We deliberately designed the `create-electric-app` package such that our docker compose creates a PG database with the name of the project, i.e. `npx create-electric-app@latest foo` expects PG to have a DB named `foo`.

How this works is:
- the generator writes the name of the app as an environment variable `APP_NAME` to `.envrc`
   ([https://github.com/electric-sql/electric/blob/main/examples/starter/src/index.ts#L76](https://github.com/electric-sql/electric/blob/main/examples/starter/src/index.ts#L76))
- our docker compose file creates a DB named after the `APP_NAME` environment variable. If that environment variable is absent it uses the default name `electric`, cf. [https://github.com/electric-sql/electric/blob/main/examples/starter/template/backend/compose/docker-compose.yaml#L15](https://github.com/electric-sql/electric/blob/main/examples/starter/template/backend/compose/docker-compose.yaml#L15)

I believe that the DB is only created the first time that the Docker image is ran.
So next time you run it (e.g. for a different project) the volumes are still there and so it does not create your new database. So the problem comes from the fact that both projects are using the same Docker image for PG and thus sharing the same database.

**Comment by thruflo** [comment]
Yes, basically the backend for the previous starter is still running.

@kevin-dp do you think the code for extracting the dynamic PG port could be a cause here -- i.e.: does it get there first matching port, when potentially multiple containers are running? If so that could actually be a simple practical fix?

**Comment by kevin-dp** [comment]
@thruflo I don't think the port is the issue. For the above bug you don't need the backend of the previous starter to be running. It suffices that you have ran the backend of the previous starter at least once in the past. Because when you ran the backend, it created a PG DB named after the name of your app.

Now, when you run the starter again for a new project, it will re-use the same Docker image for PG, it will find the volume for that image and so it will re-use the volume and hence not create a new database for your app. As a result, your new app does not find its database on PG because it was never created.

**Comment by kevin-dp** [comment]
The accepted answer in this thread is useful to understand the problem:
[https://stackoverflow.com/questions/56657683/postgres-docker-image-is-not-creating-database-with-custom-name](https://stackoverflow.com/questions/56657683/postgres-docker-image-is-not-creating-database-with-custom-name)

**Comment by thruflo** [comment]
Yup, got it, ta.

So it looks like we could avoid the clashes by prefixing the container name in the generated docker compose with the app name. I've raised [#497](https://github.com/electric-sql/electric/issues/497) to address.

**Comment by kevin-dp** [comment]
I'm closing this issue in favor of #497.

**Comment by balegas** [comment]
Being taken care of in [VAX-1087](https://linear.app/electric-sql/issue/VAX-1087/prefix-starter-template-container-name-with-app-name)
