### ISSUE TITLE
[VAX-1087] Prefix starter template container name with app name.

### ISSUE THREAD

**Issue by thruflo** [electric-sql/electric#497]
As per [https://github.com/electric-sql/electric/issues/489](https://github.com/electric-sql/electric/issues/489) et al, we currently have a clash of container names from multiple invocations of the starter template.

One fix is to prefix the container name in the generated docker compose with the app name. Basically to stop Docker from reusing the same container / volume.

<sub>From [SyncLinear.com](https://synclinear.com) | [VAX-1087](https://linear.app/electric-sql/issue/VAX-1087/prefix-starter-template-container-name-with-app-name)</sub>

**Comment by kevin-dp** [comment]
As pointed out by @alco docker prefixes container names with the name of the folder that contains the compose file. In the starter template that folder is called `compose`. We could rename it to be the app name. But then we can still run in the same issue if someone has 2 projects with the same name in different locations.

Perhaps a more robust approach is to assign unique names to the volumes.

**Comment by thruflo** [comment]
I think a clash for apps with the same name is more understandable. We're fixing some demo scripts, I suspect pulling the docker compile file into the root folder will solve 99% of the clashes.

**Comment by balegas** [comment]
Adding `name: "${APP_NAME}"` to the compose file would address the clash on 'compose'. 

But then we clash on bind ports for local host :)

I think it's sensible to provide env vars for overriding clashing ports when launching second app.

**Comment by thruflo** [comment]
Not with dynamic host ports we don't.

**Comment by balegas** [comment]
there are three possible clashes:
- root name for compose (addressable with APP_NAME)
- ports (seems alright for Pg, but a clash fdor Electric)
- volumes (this is actually more tricky, but if you can't start an app with the same name and volumes are prefixed with app name problem is solved)

**Comment by thruflo** [comment]
Another approach is to display an error when starting he backend if the container name and or ports are taken.

**Comment by davidmartos96** [comment]
There is a solution for volumes when using Docker Compose. The volume names can be prefixed with the "name" property of the compose file.
For instance this compose file will create the volumes `electric_todos_electric_data` and `electric_todos_pg_data`:
![image](https://github.com/electric-sql/electric/assets/22084723/cf4d7406-37c2-483d-a649-5f3530f20cc7)

**Comment by barbalex** [comment]
Please remember Users using the starter may not be very versed yet

**Comment by thruflo** [comment]
We could prompt "port taken, want to use NNNN"? So things will still just work™

**Comment by kevin-dp** [comment]
There are several issues here.
We discussed this with @balegas and we plan to solve them as follows.

**Issue 1:** Clash on container names that causes volumes of other Electric apps to be re-used.
**Solution:** Use a `name` in the compose file as suggested by @davidmartos96.

**Issue 2:** When running several Electric applications with Docker we will have clases on port 5133 which is used by Electric.
**Solution:** The solution to provide optimal UX is twofold:
1. At generation time (i.e. `npx create-electric-app myApp`):
- Allow user to provide the port on which Electric should run as an optional argument.
- Check that the port is free
- If not, raise a warning that the project may clash for that port as the port is already taken
- Modify template app code to use that port
- Modify `.envrc` from the template to store the chosen port
- Modify compose file to use the port from .envrc or the default port 5133 if missing.
2. At startup time:
- Check that the chosen port for Electric in `.envrc` is free
- If not, warn and ask if they would like to change to another port
- If another port is provided, modify .envrc with the new port and warn user that they need to also use that new port in the app code.

**Issue 3:** When running different Electric apps with Docker there will be several PG containers running. The script that finds the PG port won't be able to handle that currently.
**Solution:** Modify the script to find the port of the right PG container based on the name of the app (because the PG container name should now be prefixed with the app name after the fix for issue 1).

Will look into implementing this asap.

**Comment by kevin-dp** [comment]
Currently implementing 1.
Some restrictions on project names listed in the [docs](https://docs.docker.com/compose/environment-variables/envvars/):
> Project names must contain only lowercase letters, decimal digits, dashes, and underscores, and must begin with a lowercase letter or decimal digit.

So we will need to apply the same naming restrictions for projects created with `create-electric-app`.
