### ISSUE TITLE
Generated Quickstart readme miss some information

### ISSUE THREAD

**Issue by kernerdev** [electric-sql/electric#577]
When I generate a new project with `npx create-electric-app@latest my-app` and then I would like to use `yarn db:psql` then it will throw an error because of my host machine did not find the postgres cli tool -> psql.exe 

So maybe somewhere you should mention this information inside the generated README.md or somewhere else. 

The other problem when the tool is installed then I saw that the docker-compose file did not exports the postgres port (5432) to the host machine, is it intended ?

**Comment by alco** [comment]
Hi @kernerdev! Thanks for sharing your experience trying out our starter app!

We will remove the requirement of having `psql` installed on the host OS in the upcoming release. Instead, we will use `docker compose exec` to run `psql` inside the `postgres` container.

> The other problem when the tool is installed then I saw that the docker-compose file did not exports the postgres port (5432) to the host machine, is it intended ?

We do expose the port from the `postgres` container, we just let the Docker engine to pick a random port on the host OS to map it to. You can see which port it chose by inspecting the output of `docker ps`. When you run `yarn db:psql`, it pretty much does the same to get the port and then uses it to build the database URL to connect to.

The way it works is changing in the upcoming release because there we will be introducing a proxy through which DB connections will need to go to be able to use our DDLX extension to SQL. Stay tuned!

**Comment by samwillis** [comment]
This is fixed in v0.7.0, `db:psql` no uses the `psql` in the docker image.
