### ISSUE TITLE
Listener warning

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#868]
I have a view with a lot of small components that all have a small query listening for updates to their specific object — which should be a supported use case I'd assume? Or if there is an actual limit you want to warn against, set it to that. But I'm assuming the eventemitter is just set to the default (11 I think).

<img width="685" alt="Screen Shot 2024-01-22 at 1 05 49 PM" src="https://github.com/electric-sql/electric/assets/71047/66774cd7-0c8e-408e-9afa-2cc84ee0ec38">

**Comment by msfstef** [comment]
Looking at the notifier code under `src/notifiers/event.ts`, we have the following:

```ts
// Global singleton that all event notifiers use by default. Emitting an event
// on this object will notify all subscribers in the same thread. Cross thread
// notifications use the `./bridge` notifiers.
const globalEmitter = new EventEmitter()

// Increase the maximum number of listeners because multiple components
// use this same emitter instance.
globalEmitter.setMaxListeners(250)
```

This limit was increased to 250 by @thruflo int https://github.com/electric-sql/electric/pull/377 - since this is a global emitter I find it hard to think of any reasonable way to adjust this limit for a large application while still retaining the ability to detect if listeners are being accumulated or not appropriately removed. Maybe removing this warning and checking if many listeners are being added in the same "place", or having them be identified somehow could help construct a better warning.

For your particular case, would a "parent" component with view-only children work as well or would it complicate the code too much?

**Comment by KyleAMathews** [comment]
Yeah I'm sure I could refactor — I think ideally though the subscriptions are efficient enough it's not necessary.

**Comment by KyleAMathews** [comment]
I haven't noticed any slowdowns with the app & memory is fine — though all these listeners are to objects that are rarely changed. So what exactly is the upper limit is pretty arbitrary depending on what's updating in your app.

**Comment by msfstef** [comment]
@samwillis what's your take on this? I think it makes sense to remove the warning altogether as we explicitly use a global emitter - if we want to catch leaks we can implement our own tests or mechanisms from within our `EventNotifier` to catch them.
